version: "3.8"

services:
    mysql:
        container_name: Dendoelder_Portfolio
        image: mysql:latest
        volumes:
            - 'apache-mysql:/var/lib/mysql'
        ports:
            - '${FORWARDED_DB_PORT:-33061}:33061'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - dennetwork

    php-apache:
        container_name: Dendoelder_Appplication
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-81}:80'
        volumes:
            - '.:/var/www/html/'
        networks:
            - dennetwork
        depends_on:
            - mysql

    composer:
        container_name: Composer_Dendoelder
        image: composer:latest
        volumes:
            - '.:/app'
        command: >
                bash -c "composer install
                && composer update"

    node:
      image: node
      volumes:
          - './:/home/node/app'
      working_dir: /home/node/app
      command: >
              bash -c "npm install
              && npm update"
networks:
  dennetwork:
    driver: bridge

volumes:
  apache-mysql:
    driver: local
